#+title: Notes on an 11 day water fast
#+subtitle: No, you don't get hungry
#+date: 2025-11-17T05:14:59
#+tags[]: fasting health autophagy ketones weight-loss

I was getting tired, inflamed and generally fat, probably an effect of
eating too much and drinking too much so I decided to stop doing that
for 11 days.  And when you stop eating for that long, you need to
slowly "refeed", so maybe it's been more like 13 days.

Physically and more importantly mentally I feel quite refreshed.  I'm
already planning a fasting regimen as part of regular living (once I
fully get out of this one) because it's so simple and so effective.

Each morning I started the day with a nice big glass of salt water --
keeping the electrolytes balanced is the trick to making this whole
thing "easy".  If you are feeling tired, or sluggish, or whatever,
drinking a lot of water and making sure that you have enough salt is
the difference between being alive and just sort of waiting for it all
to be over.  And if you are in that later state, I would suggest just
breaking the fast since we aren't doing this for the glory or
anything.

I was incredibly productive during this time.  I got through more
house chores each weekend than I would have otherwise.  I'm juggling 5
client projects, plus 2 separate side projects, 3 different companies,
and 5 children.

My sleep wasn't great and when I do it again I'm going to focus more
on physical activity.  I came up with all sorts of excuses, but really
walking 60 minutes a day would have made a big difference, and if we
lived in the city you'd get that for free.

* What happens

First you burn through all your sugar stores.  Then your body starts
learning how to burn through fat.

This takes a while -- your body can quickly shift to pulling fat out
of storage, but cells need to transition over into the new type of
fuel source.  This can make things a bit weird at first.  My brain
cells seemed to take a few days longer than I would have wanted them
to.

Then your body starts a process called "autophagy", which literally
means "self-eating", but it's a biological process where your cells
identify damaged or unnecessary components, break them down, and reuse
their building blocks.

In other words, you use all the old crap laying around in addition to
the fat, so the cells get cleaned out also.

The idea of stopping around day 11 was that most of the benefits of
cleaning and rebuilding everything has peaked at that point, and then
you'd start consuming good lean mass to survive so it becomes
"unhealthy".

Also, I missed eating and socializing.

* Some stats

What you might expect is that you'd stop eating, and then the weight
loss would slowly start as you finished digesting everything you'd
eaten and gotten it out of your system, and then it would keep going
down.


{{< img img="estimated_weight_loss.png" fit="750x750 smart">}}

But what I actually saw was different.  Weight dropped fast initially,
which was largely "water + glycogen + gut contents.", and then sort of
plateaued.  This is water weight since I was trying to drink around 3L
of water a day.

{{< img img="morning_weight_in.png" fit="750x750 smart">}}

/The shaded area is where I started eating again/

I got a DEXA scan somewhere in the middle of this process, so I don't
really know what I started at but I estimate I lost between 2.5 and
3kg of pure fat.

* What it felt like

In the beginning it was strange, basically a high adrenaline feeling
while transitioning over to ketones, then it super sucked around days
5 because of "bile dumping", and then we moved to the other side and it
was clear sailing.

{{< img img="mood-chart.png" fit="750x750 smart">}}

Something happened around day 4 or 5, where I really starting thinking
about food.  Previous times fasting this is when I stopped, because I
think it's bananas to be thinking about food so much and not eating,
why would I fight my body like that?  I'm not looking to give myself a
complex.

But what happened is that all this bile that used to be regularly
released into the gut never got the message to go, and it was like
"I'm going now" and it was super, flaming-anus level irritating off
and on for 2 days.  If it was bad the 3rd morning I would have
stopped, but it did it's thing, and we made it to the other side.

After that it was sort of the calm state of low-yet-infinite energy.  I
felt like once I managed to start something I could keep going forever
and wouldn't feel more or less tired after.

Keto brain is worth experiencing for everyone I think.  If you suffer
from anxiety or epilepsy I could very much believe that this would
quiet the system down and you'd function better.  (I don't have those
conditions (or any that I know of) so I'm probably just talking
nonsense, but nevertheless it was super fun to experience.)

When I'd get mad or worked up about something, you could feel the
physiological effect on the system -- heart pounding, agitation, that
sort of thing -- and then it would pass by after it was over.  I can get
obsessive sometimes about things and say arguments get stuck in my
head, and this let them fly away more.

My libido dropped down to zero which sort of sucked, and I've read
that for the duration testosterone levels drop quite a lot.  Happy to
report that it comes back with a vengeance once you start eating again.


* Process

I started a ChatGPT thread telling it my plan, and told it to remind
me every morning to log my stats.  I'd weight in on the scale, or I'd
take a screenshot of my Oura ring app to upload it directly, so it
could log everything.

Very helpful.  One of the big side effects of fasting is that you want
to know a lot about fasting and asking the model random question is
much better than looking at random youtube videos.  I still don't
really understand how my weight could stay the same -- something
something, water distribution -- but I can ask it as many times as I
want.  I would never have figured out the bile thing -- I thought bile
was for digestion only, not the liver dumping waste products, and I
certainly didn't know that the bile gets reabsorbed in the small
intestine.

Do those answers matter?  Are they even true?  I don't know, but
having a companion you could ask during the process with all of your
details was super helpful.


