#!/bin/bash

directory=queue
mkdir -p ${directory}
if [ -z "$1" ]; then
    command=event=ping
else
    command=${@}
fi

time=$(date +"%Y-%m-%d-%H:%M:%S")

outfile=${directory}/${time}.job

jo ${command} > ${outfile}
cat ${outfile}
