#!/bin/env/ruby

BASE_DIR="/Users/wschenk/willschenk.com"

Dir.glob( "#{BASE_DIR}/content/*/*/*{md,org}" ).each do |page|
  puts page
  base = File.dirname( page )
  puts "base", base
  name = File.basename( page, File.extname(page))
  puts "name", name

  cmd = "mkdir -p #{base}/#{name}"
  puts cmd
  system( cmd )

  cmd = "mv #{page} #{base}/#{name}/index#{File.extname(page)}"
  puts cmd
  system( cmd )
  puts
end
