version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - type: bind
        source: ./blobs
        target: /blobs

    ports:
      - "8080:80"

  mover:
    build:
      context: .
      dockerfile: Dockerfile.mover
    volumes:
      - type: bind
        source: ./blobs
        target: /blobs

    ports:
      - "9090:8080"
