#+title: Coding with cursor
#+date: 2024-09-20T16:02:46
#+draft: true

I want to build a static app using modern javascript and html that
that uses webcomponents.  each component will live it its own file.
The task of the application is to manage assets, and it will use
supabase to do so.  When a file is dragged onto the window, that gets
added to the upload queue.  The user can also press space to record
audio, and space again to stop the recording and it will get added to
the upload queue.  The user can also press a button which lets them do
a video recording, which when stopped will get added to the upload
queue.  When something is added to the upload queue, or if the
device's network setting gets changes like they lost connectivity,
everything is first stored locally in the webbrowser as a PWA so that
the upload can resume.  There's a process bar for the uploading so the
user can see which files have been sucessfully uploaded or not



please contiue the implmentation


progress bar is referenced but not implemented



can you import subapase from <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>


wait until the window is ready event to initialize supabase



{statusCode: '403', error: 'Unauthorized', message: 'new row violates row-level security policy'}


actually can you use supabase to get the anon user when it first starts up and print it out



* References
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
