FROM node:10.16.1-stretch

USER root
RUN apt-get update && apt-get -y upgrade

RUN mkdir /usr/share/app
WORKDIR /app

RUN npm init -y && npm install --save ipfs

ENV PATH="/app/node_modules/.bin/:${PATH}"
ENV IPFS_PATH=/ipfsdata

CMD jsipfs daemon --enable-pubsub-experiment

