REPO_WORK_DIR="/repository"
REPO=ENV['REPO']

throw "Set REPO" if REPO.nil? || REPO == ""

if !File.exists?( "#{REPO_WORK_DIR}/.git" )
  puts "Ensuring that we have the repository"
  system( "git clone #{REPO} #{REPO_WORK_DIR}" )
end

file "authors.log" do
  puts "Generating authors.log"
  system( "(cd #{REPO_WORK_DIR};git log --pretty=format:\"%ae:%an\") | sort -u > authors.log" )
end

file "commits.log" do
  puts "Generating commits.log"
  system( "(cd #{REPO_WORK_DIR};git log --reverse --pretty='format:%aI|%ae|%an|%D') | sort > commits.log" )
end

task :avatars => "authors.log" do
  puts "Looking for avatars"
end

task :default => :avatars
