#+title: Building A Hugo Theme with Tailwind
#+subtitle: This is my subtitle, and I like it
#+tags[]: hugo, tailwind
#+date: 2022-09-18T13:18:38-04:00
#+draft: true

This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.

1. This is something
2. And other
3. Yup
4. Why not?

Paragraph text


- One thing
- Two things
- Three things
- Four things 

* Here are some words
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.
This is a large block of text that says stuff.


* Setting up the initial site

#+begin_src bash
hugo new site
hugo new howto/2022/building_a_hugo_theme_with_tailwind.md
hugo new theme tailblog
#+end_src

Inside of =config.toml= set

#+begin_src toml
theme = 'tailblog'
#+end_src

Now start the server!

#+begin_src
  hugo serve
#+end_src

* Creating the basic layout

=layouts/index.html=

#+begin_src html
{{ define "main" }}
{{ .Content }}

<ol>
{{ range .Site.RegularPages }}
<li><a href="{{ .RelPermalink }}">{{ .Title }}</a></li>
{{ end }}
</ol>
{{ end }}
#+end_src

=layouts/_default/single.html=
#+begin_src html
  {{ define "main" }}
  {{ .Content }}
  {{ end }}
#+end_src


* Get some styling

#+begin_src bash
  cd themes/tailblog
  npm install --save-dev tailwindcss
  npx tailwindcss init
#+end_src

Update /tailwind.config.js/

#+begin_src javascript
  /** @type {import('tailwindcss').Config} */
  module.exports = {
    content: ['layouts/**/*.html'],
    theme: {
      extend: {},
    },
    plugins: [],
  }

#+end_src

Create /input.css/

#+begin_src css
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
#+end_src

Update your package.json

#+begin_src javascript
  {
    "scripts":{
      "dev": "npx tailwindcss -i input.css -o static/css/main.css -w",
      "build": "NODE_ENV=production npx tailwindcss -i input.css -o static/css/main/output.css -m"
    },
    "devDependencies": {
      "tailwindcss": "^3.1.8"
    }
  }
#+end_src

And then /layouts/partials/head.html/

#+begin_src html
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello Hugo</title>
    <link rel="stylesheet" href="/css/main.css"> 
  </head>
#+end_src

Run =npm run dev= in a browser and you should have a tailwind styled site!
