#+title: Charging Networks Compared
#+subtitle: Ready for a NACS world
#+tags[]: tesla ev rivian
#+date: 2023-07-01

In the middle of the first road trip with the [[https://rivian.com/r1s][new Rivian]].  So far I've
charged with the following:

* Tesla Superchargers

This is easy since I'm also a Tesla owner since 2016.  Already had a
Tesla account, so just had to open the app, click the account icon,
swipe over to /Charge Your Non-Tesla/ and select a stall.

The charge point on the Rivian is the front left; the Telsa is the
back left.  This means that you park in the stall next to what you
should park in.  I'm familiar with the dynamics at the locations so I
didn't feel out of place but I know that people there felt that I did.

Superchargers are in useful places, like convenience stores or cool
malls or travel islands.

**Rating**: /Superb.  Charge speed is as expected.  Connector is solid,
locks in like it means it./  (The straight Tesla experience is still a
zillion times better.)

* Electrify America

Signed up for an account before I left since the routing software said
I'd hit a 350 kwH charger.  Woo!  Easy to setup, tap to activate
charge.  The connector was solid.  Got 74kWh into the car in 33 mins,
158 miles of range.

It does some weird "prepay for the charge thing", like easy pass where
you put money into your account and when it gets below a set level
charges your credit card before you use the money.  Maybe they plan on
making money off the float.

The charger that we ended up at was at a bank, which happened to be
one that I have an account at.  There was no bathroom available, and
it was a bit weird asking.  Ended up at the library across the street,
and then walked a couple of blocks to a Walgreens to get some snacks.
The whole thing felt sketchy.

*Rating*: /Expensive but solid experience.  App is pretty but sort of
souless.  The screen on the charger matched up with the car./

* ChargePoint

Setup a long time ago with the Tesla, you can use the phone to tap and
activate your session.  The app is the best of the lot.

However the charger that I used was in a Subaru dealership.  There
were two allegedly 125 kwH stalls: a guy crawled out from under the
car he was working on to tell me that one wasn't working.  (Nice of
him but sort of awkward.)  I only managed to get about 80 kwH out of
the other one.

The screen on the charger also showed me incorrect information,
perhaps because it was configured with my Tesla and not the car.  The
charge connector felt "mushy", it didn't click in any satifying way.

*Rating*: /Decent app experience, better locations, but charging rate and
information was misleading to total bullshit./


* EVgo

Found a lone stand out in the middle of a mall parking lot.  Tap to
activate didn't work, it thought it meant that I was trying to pay
with a credit card, which would have been fine if it had actually
worked.  Needed to call customer service to get them to activate the
charger.  It's cute that they give the chargers names, but I still
needed to read out some number thing for them to know where I was.

Also, a bunch of different cars showed up at the same time.  There was
another Rivian who was super chatty; then a Lyriq showed up and man
was that guy not happy that I was there taking up the one, very slow
charger.  The car had dealer plates so maybe he was so sour because it
was his job and he wasn't into it.

I think they are supposed to send me a card or something that I'd use
to activate a charge.  Seems stupid.

*Rating*: /Slow, disorganized, and not great./


* Blink/SemaConnect

There's a tiny charger just next to a coffee shop we happened to stop
at for lunch.  We were there for an hour and added 12 miles.  What is
the point of this existing?

Also there was no cell service and there was no way to enable it.  I
plugged in the car, ordered breakfast and downloaded the app, created
an account, entered my credit card and was able to activate it remotely.

*Rating*: /Bad user experience, super slow charger, better not to have it at all./

I assume that Blink or Sema Connect has faster chargers out there but
this was a bad introduction.

* The Supercharger network is better than I realized

I didn't realize how horrible the CCS connectors were.  I had sort of
expected that they would be onpar, but really they are huge and you
sort of need to mash them in there.  Only with Electrify America did I
feel like it was locking in something serious and actually machined
well and engineered.

The supercharging speeds are generally as expected, unless something
weird is happening at the station like it's over heated or if your car
battery is cold.  In contrast, none of the chargers that I've been to
with the Rivian (other than the Brewster Supercharger) have gotten
anything close to the charge speeds advertised.

Electify America seemed to talk to the car and figure out what's up;
all of the other ones had little idea of what the power was going
into, so the reporting and user experience on the charger itself was
misleading.  Setting up accounts is a pain, and it's clear that you
are dealing with hardware companies when you are forced to use their
mobile apps.  In otherwords, the apps are not great and it makes the
experience hard.

It would be better to scan a QR code and use Apple Pay or Google Pay
or something.

The locations of superchargers are generally at gas stations, malls,
grocery stores, or travel plazas.  Places where you feel welcome
wandering around and otherwise being part of your travel experience.
In contrast, most of the other charging locations are in weird out of
the way places, like the parking lot of the utility company or
something.  It does the job but you want to hide in the car rather
than have it be a travel experience.

Basically it feels like the supercharger network was in 2016, but with
more complicated billing and without the sense of exploring something
special.  You aren't on the "same team" as the other drivers there.

It works, but it feels very early.
