#+title: Grief is the sensation of a new person being born
#+date: 2023-04-16
#+draft: true

On January 10th, 2022, my wife Joy started to feel dizzy, sat down on
a bench, and never got up again.  The process took about 15 minutes
from her perspective and has a lot to recommend it as a way of dying.

For example: it was quick.  There was no suffering.  There was no one
at fault, no accident let anger form around.  She had stopped
breathing by the time she got to the hospital, no treatment that they
could have tried with any chance of success.  (There was about 10
hours of things in 2 different hospitals that they did try before
officially calling it, but realistically it was instantaneous.)  There
was no suffering, no anxiety, and nothing that anyone could have done.

It was a thing that happened.  We could know How it happened, but
there was no Why.

We have 3 young children, the youngest was 3 and with Joy at the time.
Most of my thoughts at the time were around them, that I was the only
person in the world that could navigate them through what was
happening, that my clear role was to take all of this chaos energy and
use it to help them understand the world that they are now in, to
create a new path that they would be on where they could still thrive,
and bend the universe around them to make it possible.

The hospital in the woods, where we live, was an isolated
technological outpost of civization in the wilderness.  It was cold
and dark outside, and warm and brightly lit inside.  They said that
there was a lot of bleeding and she was very sick.  The helicopter
flight to the hospital in the city was a life line to a larger
civization, the city it was in was a cesspool, with human caused
wounds waiting in the emergency room and a police escort to my hotel
late at night because it was a rough neighborhood.  Ultimately, both
places were there to comfort the survivors even if they didn't fix
anything.

Chaos and Necessity were concepts that I almost physically felt.
Chaos in an old greek sense, from Hesiod, a sense of boundless energy
that contained all possibilities before the ideas of discord and
strife entered into it.  Necessity was that the reality of the
situation simply demanded certain things, what I wanted or didn't want
was beside the point, the only answer was a complete acceptance of the
sitatuaion and that would allow the energy to flow unimpeded.

After 4 days I slammed back online as a totally new person.  Those
days before were spent in what I'm sure looked like shock on the
outside, but what internally felt like large things subconciously
shifting around, a massive amount of growth and change and peices of
the old me being shattered and rearranged.  I was more awake than I'd
ever been before.


