#+title: Reading email in Emacs
#+subtitle:: Lets go crazy
#+tags: howto, emacs, notmuch
#+date: 2020-06-22
#+draft: true

Mail is complicated.  Lets see what reading mail is like in emacs
before we go forth to really move things over.  We're going to pull an
export in from Google Takeout, play with mail reading inside of emacs,
send up mail sending and then finally how to keep things in sync.

* Get your mail from gmail

Go to [[https://takeout.google.com/settings/takeout][Google Takeout]] and export that gmail!  I selected everything,
50G file stored as =tgz=.  It took about 3 hours for the file to be
available to me.  I've got about 14 years of email on there and it
weighed in at 5.9G compressed, 12G uncompressed at by the time it got
to me.

Once you get the confirmation email, down that it and uncompress.
Your file will be named differently. 

#+begin_src bash
tar xzf takeout-20200622T100306Z-001.tgz 
#+end_src

* Convert =mbox= into =Maildir=

First we install the [[http://batleth.sapienti-sat.org/projects/mb2md/][mb2md]] utility, and point it at our =Takeout=
directory.  We're using debian here but I'm sure this old school
utility is available where ever Maildir processors are sold.

#+begin_src bash
sudo apt install mb2md
mb2md -s Takeout -R
#+end_src

This will take a while, especially on the Pixelbook's encrypted
disk. Grab a drink.

* Install notmuch

#+begin_src bash
sudo apt install notmuch
#+end_src

And do the initial setup.

#+begin_src bash
notmuch
#+end_src

Here you will be prompted for your name, email address, and other
basic stuff.  =mb2md= puts mail in =~/Maildir= so tell notmuch where to
look.

Once it's done, run =notmuch new= to create the index.  It says

#+begin_src bash
Found 197265 total files (that's not much mail).
Processed 2261 of 197265 files (40m 16s remaining).
#+end_src

Not sure if it always says that's not much or if it's actually not
that mail in it's understanding of /a lot of mail/. At any rate, time to
hunker down and wait a while.  In fact I had plenty of time to take
off all of the storm windows off the house, eat dinner, and by the
time I checked in on it again it was the next morning, at which point
it was definitely finished.




* Playing with notmuch

Now in emacs we can start up =M-x notmuch=.

TODO Screenshot 1

Lets create a =+sent= tag of all the email that I've sent to people and maybe that will showup in the screen shot:

#+begin_src bash
notmuch tag -inbox +sent from:Accountname@gmail.com
#+end_src

TODO Screenshot 2

That seems a bit better, but maybe there's a way to pull in the read
and unread tags in from gmail directly, so we don't have that
monstrostity of an =unread= count.



* Setup smtp

* References

1. [[https://notmuchmail.org/howto/][Notmuch Howto]]
2. [[https://takeout.google.com/settings/takeout][Google Takeout]]
3. [[http://batleth.sapienti-sat.org/projects/mb2md/][mb2md]]
4. [[https://www.youtube.com/watch?v=wuSPssykPtE][Hey.com workflows in notmuch]]
5. https://gist.github.com/vedang/26a94c459c46e45bc3a9ec935457c80f
6. https://noonker.github.io/posts/2019-12-28-nomorelockin/
