#+title: Reading PDFs in Emacs
#+subtitle: Full embrace the emacs lifestyle
#tags: howto, emacs
#+date: 2020-06-16
#+draft: true

[[https://github.com/politza/pdf-tools][PDF Tools]] is a way to interact with pdf files within emacs, and offers
at lot more functionality than the built in docviewer.  You can
increatemental search through the document, clink on links, make
annotations, and use org-mode links to go to specific annotations.


* Installation

Install some dependacies

#+begin_src bash
sudo apt-get install libpng-dev zlib1g-dev \
libpoppler-glib-dev libpoppler-private-dev imagemagick
#+end_src

The install the package: =M-x package-install RET pdf-tools=

* Confirm the installation

Test it out with:

=M-x pdf-info-check-epdfinfo=

This looks to see if you have the =epdfinfo= binary installed, the
source of which is distrubuted in the package from ELPA. I needed to
go into that directory and install it manually since the automatic
installation had some permissions issues.

This was done with the normal =./configure= and =make= process.

Once this is working, then install it in your local session:

=M-x pdf-tools-install=

Which you will eventually put in your =.emacs= file like so:

#+begin_src emacs-lisp
(pdf-tools-install)

(use-package org-pdftools
  :hook (org-load . org-pdftools-setup-link))
#+end_src


