apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  params:
    - name: service_name
      type: string
    - name: image
      type: string
  resources:
    - name: docker-source
      type: git
    - name: builtImage
      type: image
  tasks:
    - name: build-image
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: builtImage
    - name: update-service
      runAfter:
        - build-image
      taskRef:
        name: kn
      params:
        - name: ARGS
          value:
            - service
            - update
            - $(params.service_name)
            - --image
            - $(params.image)
