apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: service_name
    value: homepage
  - name: image
    value: wschenk/homepage
  resources:
  - name: builtImage
    resourceRef:
      name: homepage-image
  - name: docker-source
    resourceRef:
      name: homepage-git
  serviceAccountNames:
    - taskName: build-image
      serviceAccountName: dockerhub-service
    - taskName: update-service
      serviceAccountName: kn-deployer-account
