apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: build-homepage-
spec:
  serviceAccountName: dockerhub-service
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: homepage-git
    outputs:
      - name: builtImage
        resourceRef:
          name: homepage-image
