apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: debug
spec:
  description: >-
    This runs ls

  params:
  - name: directory
    description: Where to list
    default: ["/workspace"]
  workspaces:
  - name: source

  steps:
  - name: ls
    image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo "Hello from Bash!"
      ls -lR /workspace
