apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - bindings:
      - ref: pipeline-binding
      template:
        ref: pipeline-template
