apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-run-
  namespace: default
spec:
  params:
  - name: url
    value: https://github.com/wschenk/homepage
  serviceAccountName: ""
  taskRef:
    name: git-clone
  workspaces:
  - emptyDir: {}
    name: output
