apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kn-run-
  namespace: default
spec:
  params:
  - name: ARGS
    value:
    - service
    - update
    - helloworld-go
    - --env
    - TARGET=tekton
  - name: kn-image
    value: gcr.io/knative-releases/knative.dev/client/cmd/kn:latest
  resources: {}
  serviceAccountName: kn-deployer-account
  taskRef:
    name: kn
