apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: homepage-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/wschenk/homepage.git
    - name: revision
      value: main
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: homepage-image
spec:
  type: image
  params:
    - name: url
      value: wschenk/homepage
