#+title: Arcode chat transcript
#+subtitle: lets try them all
#+tags[]: arcode openai whisper promptprogramming
#+date: 2024-07-31T07:26:26
#+draft: true

* Installation

#+begin_src bash
  brew tap alexdredmon/arcode
  brew install arcode
#+end_src

Create a temporary directory and fire up aider

#+begin_src bash
  cd $(mktemp -d)
  echo OPENAI_API_KEY=$(op read 'op://Personal/OpenAI Key/notesPlain') > .env
#+end_src

* Run it

#+begin_src bash
  dotenvx run -- aider
#+end_src

#+begin_quote
create an express app that serves up an html and javascript files.
The app uses the media api to record a person talking, and then uses
the openai whisper api to convert the spoken text to speech.  When the
user stops the recording, there's a display that says "processing" and
when its done it gets replaced with the text that is spoken.  If
there's an error it gets displayed in that box.  openai needs to have
the right file extention so make sure its uploaded in webm and the
filename is preserved the example from the openai docs is

const openai = new OpenAI();

async function main() {
  const transcription = await openai.audio.transcriptions.create({
    file: fs.createReadStream("/path/to/file/audio.mp3"),
    model: "whisper-1",
  });

#+end_quote


* References
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
