#+title: Four freedoms
#+date: 2024-06-15T18:03:10

We went to the [[https://www.nrm.org/][Norman Rockwell Museam]] today, and there was an inspired
paring of a [[https://www.nrm.org/2023/11/mad/#exhibition][MAD exhibition]].  Did you know that [[https://www.dc.com/mad][MAD Magazine]] still
exists?  Me neither.

American Ideals at their finest.

One thing that I didn't know about was the [[https://www.nrm.org/2012/01/norman-rockwells-four-freedoms/][Four Freedoms]]:

1. [[https://www.nrm.org/2016/11/freedom-speech-1943-2/][Freedom of Speech]]
2. [[https://www.nrm.org/2016/11/freedom-want-1943/][Freedom from Want]]
3. [[https://www.nrm.org/2016/11/freedom-fear-1943/][Freedom from Fear]]
4. [[https://www.nrm.org/2016/11/freedom-worship-1943/][Freedom of Worship]]

These images captured something that is embedded in my psyche --
especially Freedom of Speech, which I think of everytime someone posts
to the local town mailing list with whatever their take is on
something.  Freedom from Want -- which is a picture of a large
thanksgiving turkey is probably the reason why I think we need to have
turkey on thanksgiving.  On any other day I'm not sure I'd ever order turkey.

The other funny thing about this is that I'd only heard of "four
freedoms" in the context of [[https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Essential_Freedoms_of_Free_Software][Freedoms of Free software]]:

#+begin_quote
Freedom 0: The freedom to use the program for any purpose.

Freedom 1: The freedom to study how the program works, and change it
to make it do what you wish.

Freedom 2: The freedom to redistribute and make copies so you can help
your neighbor.

Freedom 3: The freedom to improve the program, and release your
improvements (and modified versions in general) to the public, so that
the whole community benefits.
#+end_quote

