#+title: Setting and using Aerospace
#+subtitle: moving away from the mouse
#+tags[]: aerospace osx
#+date: 2025-06-28T19:57:33

#+begin_src bash
  brew install --cask nikitabobko/tap/aerospace
#+end_src

And the run it

=CMD-SPACE-Aero=

Then everything goes crazy.

* Move applications to a workspace

By default there are a lot of workspaces defined in your
=aerospace.toml= file, so lets take advantage.  You can do =OPTION-1= to
switch to 1, =OPTION-E= to switch to E, etc.  (You'll see which one you
are on in the menu bar.)  For the window that has the focus, doing
=OPTION-SHIFT-E= moves the window to that workspace, keeping you in the
existing one.  Go down the list and move the applications where you
want them.

For example, I'm using 

#+ATTR_HTML: :class table table-striped
| Workspace | Application         |
| A         | ChatGPT, Claude     |
| B         | Browser             |
| D         | Docker Desktop      |
| E         | Emacs               |
| M         | Mail                |
| N         | Obisidian           |
| Q         | Preview             |
| S         | Slack               |
| T         | Terminal/Warp       |
| V         | Books               |
| U         | Unread              |
| W         | Whats App, Messages |

But that's all personal preference.

* Managing windows: Tiling

There are two different layouts, tiling and accordian.  =OPTION-/= flips
between horizontal and vertical mode.

The VI movement keys -- =H, J, K, L= -- move around.  So =OPTION-H=,
=OPTION-J= will let you navigate through the windows.

Adding the shift key will move them around.

* Service mode

If you want to "move a window into another window", which while make
them tile together, enter service mode.  Which is =OPTION-SHIFT-:=.
This is how you have different layouts.

You can also go to service more press escape to reread the config
file.

* Resizing

You can make the windows smaller and bigger using =-= and ===.  This can
be handy.

* Layout: Accordian

For Books, I like the accordian layout.  This is =OPTION-,= and it puts
the windows on top of each other.  You can change focus by =OPTION-H= or
=OPTION-J= -- left and right.

* Flipping back and forth

=OPTION-TAB= goes back and forth to the previous workspace, which is
certainly something to do when you are looking at code previews.

* Editing the config file

In the menubar, there's an option to open up the =config.toml= in your
favorite editor, as well as saving it.

* References

1. https://nikitabobko.github.io/AeroSpace/guide#installation
   
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
