#+title: Things I love about my phone
#+date: 2024-03-24T10:00:43

Lets not forget how cool smart phones are.

I can open up WhatsApp and send a message, and the person on the other
side will recieve it.  I could be walking in the woods when a thought
occured to me, and they could be on an entirely different continent,
and it doesn't matter.

I really like ordering stuff on the go, like when I'm waiting for an
elevator and I make a quick order of, say, some mechanical pencils.
And then later it'll just show up.

Other things are mixed.  Looking up information and having it all at
your fingertips sometimes pulls you out of yourself. Do I really need
to know what mechanical sand is made out of, for example, rather just
be playing with it?  Are the opening hours of the store actually up to
date on google?  (Surprisingly, often not.)  And often the response
you get back is bullshit, which is to say both definitively stated and
also wrong.

But still, being able to reach out to any connection anytime anywhere
on the planet is still mindblowing.  I can remember a time when you
needed to schedule and coordinate when you'd make an expensive long
distance call, and more often than not you'd simply be uncontactable
for days or weeks.
