service: sampleapp
image: wschenk/sampleapp

servers:
  - 95.216.175.53

registry:
  username: wschenk
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  remote:
    arch: amd64
    host: ssh://root@95.216.175.53

accessories:
  redis:
    image: redis:latest
    roles:
      - web
    port: "36379:6379"
    volumes:
      - /var/lib/redis:/data
env:
  REDIS_URL: redis://95.216.175.53:36379/1
