#+title: No Snow 1948
#+subtitle: birth of snowmaking
#+date: 2025-02-09T06:36:40

Read this in the local paper about the local ski mountain, and the
birth of snow making.

#+begin_quote
In Mohawk’s second season, Mohawk did not get any snow and resorted to
ordering several tons of ice blocks, crushing them and spreading them
on the slopes. This process was time consuming, costly and overall a
worse experience than real snow. From this season, Shoenknecht got the
idea to look into snowmaking. Shoenknecht enlisted the help of the TEY
Manufacturing company, run by Wayne Pierce, Dave Richey and Art
Hunt. The three engineers used the research of Ray Ringer to build the
first snow making machines. These machines were brought to Mohawk and
are the first documented case of a trial run of the snow making
machine.
#+end_quote

[[https://lakevillejournal.com/examining-mohawk-mountains-rich-history][Examining Mohawk Mountain’s rich history - The Lakeville Journal]]

This winter has been a real one -- so much better than last year,
there's actual snow on the ground for the last few weeks.  The ponds
are frozen over, ready for ice skating.
