#+title: Adapting to new mediums
#+date: 2024-06-09T12:40:51

#+begin_quote
Technologies are aritificial, but - paradox again - artificiality is
natural to human beings.  Technology, properly interiorized, does not
degrade human life but on the contrary enhances it... such shaping of
a tool to oneself, learning a technological skill, is hardly
dehumanizing. The use of a technology can enrich the human psyche,
enlarge the human spirit, and intensify its interior life.
#+end_quote
-- Walter Ong [[https://monoskop.org/images/d/db/Ong_Walter_J_Orality_and_Literacy_2nd_ed.pdf][Orality and Literacy, pg 81-82]].

#+begin_quote
How long did it take for humans to interiorize writing and its tools?
How long will it take for us to interiorize the network?
#+end_quote
-- Jeff Jarvis [[https://www.bloomsbury.com/us/gutenberg-parenthesis-9781501394829/][Gutenberg Parenthesis]]

#+begin_quote
In the beginning, there were ABC, NBC, and CBS, and they were
good. Midcentury American man could come home after eight hours of
work and turn on his television and know where he stood in relation to
his wife, and his children, and his neighbors, and his town, and his
country, and his world. And that was good. Or he could open the local
paper in the morning in the ritual fashion, taking his civic communion
with his coffee, and know that identical scenes were unfolding in
households across the country.
#+end_quote
-- [[https://harpers.org/archive/2021/09/bad-news-selling-the-story-of-disinformation/][Bad News Selling the story of disinformation by Joseph Bernstein]]

