#+title: I need a trigger warning
#+date: 2024-04-30T21:53:06

All of these protests and the war in gaza has brought up all the old
feelings of being in that [[https://www.nytimes.com/1985/12/28/world/airport-terrorists-kill-13-and-wound-113-at-israeli-counters-in-rome-and-vienna.html][terrorist attack in Rome]] when I was 8, and I
just spent 2 hours searching for this passage by Fredrick Douglass
that I read, what?  30 years ago in high school?  Memory is weird.

#+begin_quote
My mistress was, as I have said, a kind and tender-hearted woman; and
in the simplicity of her soul she commenced, when I first went to live
with her, to treat me as she supposed one human being ought to treat
another. In entering upon the duties of a slaveholder, she did not
seem to perceive that I sustained to her the relation of a mere
chattel, and that for her to treat me as a human being was not only
wrong, but dangerously so. Slavery proved as injurious to her as it
did to me. When I went there, she was a pious, warm, and
tender-hearted woman. There was no sorrow or suffering for which she
had not a tear. She had bread for the hungry, clothes for the naked,
and comfort for every mourner that came within her reach. Slavery soon
proved its ability to divest her of these heavenly qualities. Under
its influence, the tender heart became stone, and the lamblike
disposition gave way to one of tiger-like fierceness. The first step
in her downward course was in her ceasing to instruct me. She now
commenced to practise her husband's precepts. She finally became even
more violent in her opposition than her husband himself. She was not
satisfied with simply doing as well as he had commanded; she seemed
anxious to do better.
#+end_quote

- CHAPTER VII of Narrative of the Life of Frederick Douglass
