#+title: My physical relationship to the internet
#+date: 2024-03-14T10:28:09

Where I live there is very spotty cell service.  If I'm not connected
to WiFi at home or at the market, my connectivity to everyone is sort
of fire and forget -- the messages will go out, the messages will come
it, but not immediately.

The feeling is what I go over the hill and all of a sudden my phone
blows up with notifications, then I'm off grid for the next few miles.

Coverage is not better inside, or on the road or something -- I get
better service way out in the woods behind my house than I do on the
town green.

I'm used to this reality that its jarring when I take the train back
to the city.  At first, coverage is really bad on the train.  I'll
tether the laptop to the phone, and watch the packet loss slowly
improve right up until I get to grand central.

At home, everything is downloaded to the phone.  PocketCasts streaming
feature is basically pointless for me, I need to wait till it's
downloaded before getting in the car.

When I get to the city, the process is inverted.  Why would I connect
to the hotel's WiFi when it's so much easier and more reliable to
tether through the phone?

The internet on my home turf is more like being in an airplane -- it
works under certain situations, but it needs to be offline first.
