#+title: Vacation Book Reading
#+date: 2024-07-08T08:28:52

Spent a few weeks in Spain, managed to get some good reading in!


* [[https://bookshop.org/a/5349/9781501394829][The Gutenberg Parenthesis: The Age of Print and Its Lessons for the Age of the Internet]] (2023)

Hard to get into, but once you are there worth the read.  The biggest
take away for me was the idea of "the mass" as being created by the
medium, so people reading (say) twitter all of a sudden become this
group, which doesn't really have an existance, but, like Santa Claus,
changes everyones reality.

* [[https://bookshop.org/a/5349/9780593321201][Tomorrow, and Tomorrow, and Tomorrow]] (2002)

Expected very little of this, got much more than expected.

* [[https://bookshop.org/a/5349/9780765302786][A Stainless Steel Trio: A Stainless Steel Rat Is Born/The Stainless Steel Rat Gets Drafted/The Stainless Steel Rat Sings the Blues]] (1985)

Its funny to reread these books when you are older and get all of the
references.  Really holds up, both as a satire on the Heinlien
adventure-boy genre, but as an interesting discussion on how to fit
inbetween places.  It's a very impressive feat to put so much
philosophy and sociology in a page turning absurdist caper plot that
keeps 12 year old's attentions.

* [[https://bookshop.org/a/5349/9781880100370][The Latchkey Murders]] (2015)

Since Ksenia is Russian I have a new appreciation of the Russians and
Soviets.  Not totally satisfying as a mystery, but felt like I got a
glimpse into Moscow in the 60s.

* [[https://pragprog.com/titles/mvhtmx/server-driven-web-apps-with-htmx/][Server Driven Webapps with HTMX]] (2024)

As far as server side JavaScript frameworks go, this is exceedingly
clever but I'm not sure that it really makes things simplier.

* [[https://bookshop.org/a/5349/9780062435286][Wintersmith]] (2015)

Ah... English and their distain for the wrong sort of hemegonic
thought.  In many ways the same sort of book as the Stainless Steel
Rat -- satire and commentary under the guise of silliness, as a way to
harmlessly subvert the -- but ultimately just one thing after another.
Fun if you are in the right sort of mood.

* [[https://bookshop.org/a/5349/9781611808094][Cynicism and Magic: Intelligence and Intuition on the Buddhist Path]] (2021)

I can't possibly do much justice.  The smallest book that took the
longest to read. Very interesting to see the early ways and how of how
Buddhism got into the states, and also so many important reminders.

* [[https://bookshop.org/a/5349/9781416570981][Deja Dead]] (2007)

What's funny about this book is that it spawned an empire, and reading
just the first one you'd never really expect it.  Also a bit of time
travel here since it's in the precell phone days and it's hard to find
anyone.

* [[https://archive.org/details/surfingoninterne00herz][Surfing the Internet]] (1995)

This book was amazing -- both obscure and also exactly of my world, I
knew all of the references and all of the things they talked about and
I had forgotten so much.  Was also interesting the interview with what
we would now call an incel, but before the time when the sadness had
turned into hostility towards these losers.  I very much respected
this author and tracked down a whole bunch of other stuff she wrote.

* [[https://bookshop.org/a/5349/9780063098824][The Enigma of Room 622]] (2023)

An absurd story inside of a dumb story wrapped in a magical outer
story that brought it all home at the end.  I do want to read more of
his work, but not in a rush.

* [[https://www.gutenberg.org/ebooks/51060][Narrative of Auther Gordon Pym of Nantucket]] (1838)

Poe invented nearly everything!  The so-called ending of this book is
infuriating, but the ripples of it have influenced so much.  Its the
sort of book that's a key to understanding a whole bunch of other
books, so necessary in a complete-your-education sort of way, but
without the context it's a bit strange.

* [[https://bookshop.org/a/5349/9780062206299][The Prisoner of Heaven]] (2013)

I never heard of [[https://www.carlosruizzafon.co.uk/][Carlos Ruiz Zafón]] before but picked it up in a small
english section of a Benidorm bookstore, very clever, moody and oddly
soothing.  Will go through the rest of his oevre.

* [[https://bookshop.org/p/books/homage-to-catalonia-george-orwell/16287405?ean=9780544382046][Homage to Catalonia]] (1938)

Reading Orwell after reading both the Gutenberg Parenthesis and
reflected on Foucaults 40 years was a tremendous experience and I look
at intellectual efforts completely differently now, and honestly feel
better about the state of the world than I did before.  With the
Supreme Court making kings and the farce of the elections its not
getting worse; its actually the same as it ever was and we were just
fed a load of /liberal democracy/ nonsense all this time, and it's
capital and power all along.
