# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby "2.6.6"

# gem "rails"

gem "irb", git: "https://github.com/ruby/irb"

gem "bundler", "~> 2.1"

gem "gems", "1.1.1"
