#+title: Creating a start page
#+subtitle: launch pad for all the things
#+tags[]: static_site start_page
#+date: 2024-09-09T12:07:49

* Get the repo

Head over to [[https://github.com/xvvvyz/tilde]] and fork that repo.

Then go to =Settings= > =Pages= > =Deploy from Branch= > =main=

Go back to the main repo and press =,= to open up a codespace.

* Edit the landing apges

Do =git rm CNAME= to remove the custom domain

Then open up a live server

#+begin_src bash
  pnpx live-server
#+end_src

* Edit =index.html=

Reading through the code it's pretty clever what it does, but the main
part of customization is to edit the =COMMANDS= array.

Here's a little example of what I did to expand out the github
suggestions.

#+begin_src javascript
  const COMMANDS = {
      //....
      ['g', { name: 'GitHub', searchTemplate: '/search?q={}', suggestions: 
              ["g:wschenk", "g:willschenk", "g:repos", "g:stars", "g:codespace"],
              url: 'https://github.com' }],
      ['g:wschenk', { url: "https://github.com/wschenk"}],
      ['g:willschenk', { url: "https://github.com/wschenk/willschenk.com"}],
      ['g:repos', { url: "https://github.com/wschenk?tab=repositories"}],
      ['g:stars', { url: "https://github.com/wschenk?tab=stars"}],
      ['g:codespace', {url: "https://github.com/codespaces"}],
  }
#+end_src

Which will give you something like this:

{{< img img="screenshot.png" >}}

* Save and push

Simply write a commit message, then push to origin, and there you go.
You can kill the code space or just close it and let it close itself.

If you are using chrome, the best I've figured out is to set this as
the home page.  Open up the settings and under =Appearance= set it to
your URL:


{{< img img="homesetting.png" >}}


* References

1. https://github.com/xvvvyz/tilde
   
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
# End:
