FROM golang:1.15.6-buster
RUN apt-get update
RUN apt-get -y --no-install-recommends install imagemagick ffmpeg sox build-essential git ca-certificates #postgresql postgresql-client

ENV GOPATH=/go
WORKDIR /app

RUN git clone https://github.com/majestrate/nntpchan --depth=1
WORKDIR /app/nntpchan
RUN make
CMD ./srndv2 run
