#+title: Getting Websters
#+subtitle: More glorious language
#+date: 2020-07-30
#+tags[]: emacs, howto, language
#+aliases[]: /articles/2020/getting_websters

A few years ago I read a [[http://jsomers.net/blog/dictionary][great post about the value of a good
dictionary]], which I installed on my laptop and then promptly forgot
about.  The post is very moving, and I recommend checking it out.

It was [[https://irreal.org/blog/?p=9035][recently mentioned]] on the planet emacs blog circuit and so I
thought I'd document how to get it up and running on my laptop.

Also I don't understand what the appeal of John McPhee's writing, I've
tried a few of his books but found them all so plodding.  Perhaps it's
because I'm not savoring the sentences enough...

* Get the dictionary

We are going to download the dictionary from [[http://jsomers.net/blog/dictionary][J Somer's S3 bucket]].
Uncompress this thing (which looks like an MacOS Application) then
uncompress the dictionary inside, and move it to a newly created
=~/.stardict/dic= directory.

#+begin_src bash
mkdir -p ~/.stardict/dic
cd /tmp
wget https://s3.amazonaws.com/jsomers/dictionary.zip
unzip dictionary.zip
tar -xjf dictionary/stardict-dictd-web1913-2.4.2.tar.bz2 
mv stardict-dictd-web1913-2.4.2 ~/.stardict/dic/
#+end_src

* Install stardict

Using debian, you need to install the =sdcv= command package.  Emacs
will talk to this once we are all up and running.

#+begin_src bash
sudo apt install sdcv -y
#+end_src

Test this with =sdcv billow= or whatever word you fancy.

* Install =sdvc-mode=

#+begin_src bash
cd ~/.emacs.d
wget https://raw.githubusercontent.com/gucong/emacs-sdcv/master/sdcv-mode.el
#+end_src

And then in your =.emacs= file:

#+begin_src emacs-lisp
(load-file "~/.emacs.d/sdcv-mode.el")
(global-set-key (kbd "C-c s") 'sdcv-search)
#+end_src

This binds =C-c s= to search, or you can use =M-x sdcv-search= to look up
the word you want -- or a word that you lack the power or knowledge
of.

* References
1. http://jsomers.net/blog/dictionary
2. https://irreal.org/blog/?p=9035
3. http://mbork.pl/2017-01-14_I'm_now_using_the_right_dictionary
