#+title: Upgrading emacs on debian
#+subtitle: fixing crashes
#+tags[]: emacs, debian
#+date: 2020-06-28
#+aliases[]: /articles/2020/upgrading_emacs_on_debian

Been playing with [[https://github.com/skeeto/elfeed][elfeed]] on Emacs 26.1 on =buster= and it keeps crashing.  I think for [[https://www.reddit.com/r/emacs/comments/elswgh/emacs_crashes_when_running_mu4e/][font related reasons]].  So lets follow the [[https://www.emacswiki.org/emacs/EmacsSnapshotAndDebian][Emacs Wiki Instructions]] to upgrade to =emacs-snapshots= and see if that helps.

* Add the snap shot repository.
Make sure you have the tools installed so that apt can do it's
internet thing.

#+begin_src bash
sudo apt-get install software-properties-common
sudo apt-get update
#+end_src

Add the signing key:

#+begin_src bash
wget -q http://emacs.ganneff.de/apt.key -O- | sudo apt-key add
#+end_src

And add the packages to your local index.  Note that I'm specifically
using =buster= here so update that if you need do.

#+begin_src bash
sudo add-apt-repository "deb http://emacs.ganneff.de/ buster main"
sudo apt-get update
#+end_src

* Remove the old emacs

I ran into a bunch of problems with the old emacs being installed at
the same time, and it borked =dpkg= for a bit.  So first lets remove
everything:

#+begin_src bash
sudo apt remove emacs-bin-common emacs-gtk
#+end_src

* Add the new one
Pretty straightforward here.

#+begin_src bash
sudo apt-get install emacs-snapshot 
sudo update-alternatives --config emacsclient
#+end_src

* Fix that icon

The snapshot build has a svg icon, which the Chromebook doesn't seem
to like.  So lets fix that up.

#+begin_src 
mkdir -p ~/.local/share/applications/
cp /usr/share/application/emacs-snapshot.desktop ~/.local/share/applications
#+end_src

And then edit =~/.local/share/applications/emacs-snapshot.desktop= to
put the Icon to the final image place, in my case

=Icon=emacs=

It took a while for the changes to take but after a reboot it works
great.

* Start it up

[[https://www.reddit.com/r/Crostini/comments/bw7b99/how_does_crostini_adding_icons_to_the_shelf/][Crositini will eventually update the shelf]] but it will take a little
time.

So far, no issues and no crashes!
