# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sqlite3", "~> 1.7"
gem "sinatra", "~> 4.0"
gem "puma", "~> 6.4"
gem "rerun", "~> 0.14.0"
gem "rackup", "~> 2.1"
gem "sinatra-activerecord", "~> 2.0"
