# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 3.0"
gem "puma", "~> 6.3"

gem "rerun", "~> 0.14.0", :group => :development

gem "mrsk", "~> 0.13.2", :group => :development

gem "redis", "~> 5.0"
