#+title: Quality Code Swearing
#+subtitle: more profanity the better
#+date: 2024-10-01T19:24:18

#+begin_quote
One of the most fundamental unanswered questions that has been bothering mankind
during the Anthropocene is whether the use of swearwords in open source code is positively
or negatively correlated with source code quality. To investigate this profound matter we
crawled and analysed over 3800 C open source code containing English swearwords and
over 7600 C open source code not containing swearwords from GitHub. Subsequently,
we quantified the adherence of these two distinct sets of source code to coding standards,
which we deploy as a proxy for source code quality via the SoftWipe tool developed in our
group. We find that open source code containing swearwords exhibit significantly better
code quality than those not containing swearwords under several statistical tests. We
hypothesise that the use of swearwords constitutes an indicator of a profound emotional
involvement of the programmer with the code and its inherent complexities, thus yielding
better code based on a thorough, critical, and dialectic code analysis process.
#+end_quote

[[https://cme.h-its.org/exelixis/pubs/JanThesis.pdf][Bachelor’s Thesis of Jan Strehmel]]
