# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rerun", "~> 0.14.0"
gem "roda", "~> 3.83"
gem "puma", "~> 6.4"
gem "sequel", "~> 5.83"
gem "sqlite3", "~> 2.0"
gem "dotenv", "~> 3.1"

gem "roda-mailer_preview", "~> 0.1.2"

gem "mail", "~> 2.8"
