require 'dotenv/load'

namespace :db do
  desc "Migration the database"
  task :migrate do
    puts "Calling db:migrate"
    require_relative 'db.rb'
    version = nil
    
    Sequel.extension(:migration)
    
    # Perform migrations based on migration files in a specified directory.
    Sequel::Migrator.apply(DB, 'db/migrations')
    
    # Dump database schema after migration.
    #Rake::Task['db:dump'].invoke
  end
end
