#+title: The Solemn Silence of Written Words
#+subtitle: Plato on Socrates
#+date: 2025-07-15T03:47:14
#+draft: true

#+begin_quote
I cannot help feeling, Phaedrus, that writing is unfortunately like
painting; for the creations of the painter have the attitude of life,
and yet if you ask them a question they preserve a solemn silence. And
the same may be said of speeches. You would imagine that they had
intelligence, but if you want to know anything and put a question to
one of them, the speaker always gives one unvarying answer. And when
they have been once written down they are tumbled about anywhere among
those who may or may not understand them, and know not to whom they
should reply, to whom not: and, if they are maltreated or abused, they
have no parent to protect them; and they cannot protect or defend
themselves.

And so it is with written words; you might think they spoke as if they
had intelligence, but if you question anything that has been said
because you want to learn more, it continues to signify just that very
same thing forever. When it has once been written down, every
discourse rolls about everywhere, reaching indiscriminately those with
understanding no less than those who have no business with it, and it
doesn't know to whom it should speak and to whom it should not. And
when it is faulted and attacked unfairly, it always needs its father's
support; alone, it can neither defend itself nor come to its own
support.
#+end_quote

via [[https://blog.ayjay.org/oh-the-irony/][THE HOMEBOUND SYMPHONY]]
