#+title: psychasthenia
#+subtitle: doomscrolling and qanon
#+date: 2025-08-29T04:25:26

[[https://www.jstor.org/stable/2177575?seq=1][William James' The Energies of Men]] has added a new lens through which
to evaluate people's behavior.

The gist of it is that the vitality and effort we use in day-to-day
life is far below our potential and we have Latent or reserve energy,
which are hidden stores of power that remain untapped under normal
conditions but can be released in moments of crisis, inspiration, or
extraordinary effort.

A phenomenon of “second wind”.

Ok great, but what's really interesting is that he splits our
/energies/, plural, into 4 categories:

- *Physical energy*: Bodily stamina and endurance that can be pushed far
  beyond initial fatigue.
- *Intellectual/mental energy*: Powers of reasoning, focus, and
  creativity that often lie dormant.
- *Moral energy*: Strength of will to resist temptation, overcome fear,
  or persist in difficult tasks.
- *Spiritual energy*: Higher states of devotion, faith, or transcendence
  that reorganize and elevate the whole personality.

Our current vernactular is so poor when talking about the /fatigue/
states of any of these types of energies.  Our best terms are things
like "burn-out" or "doomscrolling" or "misinformation".  (As opposed
to a dissociated state.)

They then had a term [[https://en.wikipedia.org/wiki/Psychasthenia][/psychasthema/]] -- term coined by [[https://en.wikipedia.org/wiki/Pierre_Janet][Pierre Janet]] --
entailing low psychological tension and an impotence of adaptation to
reality.

Which immediately made me think of doomscrolling and QAnon.

