apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-tls
  namespace: favoriteapp
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'k8.willschenk.com'
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.YOUR.DOMAIN'
