# fly.toml app configuration file generated for wschenk-n8n on 2024-09-09T09:12:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wschenk-n8n'
primary_region = 'ewr'

[build]
  image = 'docker.n8n.io/n8nio/n8n'

[env]
  N8N_HOST = 'wschenk-n8n.fly.dev'
  WEBHOOK_URL = 'https://wschenk-n8n.fly.dev'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/.n8n'
  initial_size = '1gb'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
