#+title: Grief is the sensation of a new person being born
#+subtitle: thriving after death
#+date: 2023-04-16
#+draft: true

On January 10th, 2022, my wife Joy started to feel dizzy, sat down on
a bench, and never got up again.  The process took about 15 minutes
from her perspective and has a lot to recommend it as a way of dying.

For example: it was quick.  There was no suffering.  There was no one
at fault, no accident let anger form around.  She had stopped
breathing by the time she got to the hospital, no treatment that they
could have tried with any chance of success.  (There was about 10
hours of things in 2 different hospitals that they did try before
officially calling it, but realistically it was instantaneous.)  There
was no suffering, no anxiety, and nothing that anyone could have done.

* We know how, but we don't know why

We have 3 young children. The youngest was 3 and with Joy at the time.
While the dieing process was short for Joy, for me it was a 10 hour
tearing down of the [[https://www.vedanet.com/the-meaning-of-maya-the-illusion-of-the-world/2018/][Maya Illusion]] culminating in the Neuro-ICU where
the doctor very gently explained to me that she was brain dead.  The
life that we had together died as well that day, a core identity was
shattered and I was left with a lot of pieces floating around, no
longer quite fitting together.

My initial thoughts were all focused on the children.  It wasn't even
that much about Joy herself, that was a done deal and a thing so big
it could only be accepted, like a great hurricane or tsunami that
destroyed a city, an event so far beyong any human agency that you
just had to figure out how to navigate through the changed world.

It was more about the kids emotional machinery not being developed,
that suddenly their basic needs weren't being met, and that I was the
only person in the world that could navigate them through what was
happening.  My clear role was to take all of this chaos energy and
use it to help them understand the world that they are now in, to
create a new path that they would be on where they could still thrive,
and bend the universe around them to make it possible.

* The wilderness

The hospital where we live, in the woods, was an isolated
technological outpost of civization in the wilderness.  It was cold
and dark outside, and warm and brightly lit inside.  They said that
there was a lot of bleeding and she was very sick.  She was airlifted
to a larger hospital in the city, a life line to the larger
civization.  The city it was in was a cesspool, with human caused
wounds waiting in the emergency room and a police escort to my hotel
late at night because it was a rough neighborhood.

Ultimately, both hospitals were there to comfort the survivors even if
they didn't fix anything.

The difference between the city and the country recurred throughout.
Farmers and hunters know about death in a way that office workers
don't.  We still go through about a gallon of milk everyday, so I'm at
the dairy farm a lot.  I'd talk to the farm hands about trying to
focus on the new possibilities that opened up, and they'd nod and talk
about opporunities.  The coyotes still howl in the night and the bears
still get into the garbage, so the wilderness isn't abstract.

* Experience of time

After 4 days I slammed back online as a totally new person.  Those
days before were spent in what I'm sure looked like shock on the
outside, but what internally felt like large things subconciously
shifting around, a massive amount of growth and change and peices of
the old me being shattered and rearranged.  I was more awake than I'd
ever been before.

1. This was a jolt of energy and there was a way to thrive.
2. I was the key person that the kids would rely upon going forward,
   especially in the beginning when we needed to act as a single unit.
3. One very big thing had changed for the kids, and so as much as
   possible nothing else should change.
4. Straightforward honest answers to questions -- to the specific
   question that was asked without any mealy mouth bullshit is the
   only path forward.

Chaos and Necessity were concepts that I almost physically felt.
Chaos in an old greek sense, from Hesiod, a sense of boundless energy
that contained all possibilities before the ideas of discord and
strife entered into it.  Necessity was that the reality of the
situation simply demanded certain things, what I wanted or didn't want
was beside the point, the only answer was a complete acceptance of the
sitatuaion and that would allow the energy to flow unimpeded.

The kids went through roughly 3 different phases, each which was about
2 weeks long.  The first was an informational gathering phase, where
they would act very literal questions about what happened.  These
questions were about things like blood and organs and what happens to
the body and various things around being alive or not alive.  For an
adult who is responding to them what's the most shocking is that they
have no existential weight, it will be some ground shaking question in
the middle of a series of chatter, and its really about collecting
matter of fact information.

A funny moment in this had to do with organ transplants.  They wanted
to know if her heart was still beating, and I said that she was an
organ donor so her body was being kept alive even through she was
dead.  So the heart was beating and she was breathing but her brain
was dead.  What does each organ do?  We went through a few of those,
and then they wanted to know if she could have a brain transplant, and
if she did they she would be the same on the outside but different on
the inside, which was exactly the opposite of the spell that Harry
Potter and friends used to sneak into Slytherin.

Also, if most of her organs were working but one wasn't, that meant
that while she was dead she was "mostly alive."  So we got in a bit of
fractions there also.

The next few weeks was about processing, just trying to put things
together.  They had collected the information, and then they were
assembling it with what they knew.  I'm not sure that it actually hit
them at this point, especially the youngest (who was 3), outside of
the talk they were reacting more like she had gone on a long trip and
that they wanted to talk with her.

