FROM golang:1.15.6-buster as build

ENV GOPATH=/go
WORKDIR /app

RUN git clone https://github.com/majestrate/nntpchan --depth=1
WORKDIR /app/nntpchan
RUN make

RUN apt-get update
RUN apt-get -y --no-install-recommends install imagemagick ffmpeg sox ca-certificates
#build-essential git ca-certificates

#WORKDIR /app

CMD ./srndv2 run
