name: Build and Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: wschenk/testimage
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
      -
        name: Run Tests
        run: docker run ${{ steps.docker_build.outputs.digest }} sh /app/fail_test.sh
      -
        name: Build and push
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
