#+title: a good death
#+date: 2023-08-23T07:03:18
#+tags[]: death

On January 10th 2022 my wife Joy started to feel dizzy, sat down on a
bench, and never woke up again.

I think it's the best way to die, suddenly, quickly, without any pain
or anxiety about what is going to happen or how a life was led.

There was nothing leading up to it, and nothing to be done.  No
decisions to be made, nothing to second guess, no one to blame.

She was with our youngest son at the time, and if it had happened 10
minutes sooner she would have been driving.  Maybe the little guy
would have been hurt, and it certainly would have been much more
confusing to figure out what happened.  She was a terrible driver so
if she had drifted off at the wheel I would have blamed her.

From her point of view, it was a short an anxiety free as it could
have been.  From our point of view, the fact that there was nothing
that could have been done made it easy to accept -- it was so shocking
and in an "act of god" territory that all you could do was accept
it. Every sort of what-if thought was shut down by the enormity of
reality.

It was very pure.
