#+title: bad analogies
#+tags[]: language, mastodon
#+date: 2023-07-09T09:30:53

* Twitter as town square

{{< toot "writing.exchange" 110677525240867713 >}}

* Mastodon is confusing

#+begin_quote
Mastodon is inherently too confusing for mass market adoption, and in
ways that can’t be fixed without some central authority coming in and
imposing a solution, which is against the fediverse’s ethos. That
doesn’t mean Mastodon is doomed or bad. Just that it’s never going to
achieve mainstream popularity.

[[https://daringfireball.net/2023/07/threads][Daring Fireball: Threads]]
#+end_quote


{{< toot "cosocial.ca" 110668640082192185 >}}

* Twitter is mainstream

Twitter is actually very confusing and while it seems big in amongst
the chattering classes, it certainly hasn't achieved "mainstream
popularity".

Compare:

| Facebook          | [[https://www.statista.com/statistics/264810/number-of-monthly-active-facebook-users-worldwide/][2.98 billion]] |
| WhatApp           | [[https://www.bankmycell.com/blog/number-of-whatsapp-users/][2.78 billion]] |
| Instagram         | [[https://www.demandsage.com/instagram-statistics/#:~:text=Instagram%20Monthly%20Active%20Users%20(MAUs,by%20the%20end%20of%202023.][2.35 billion]] |
| iMessage          | [[https://www.usesignhouse.com/blog/imessage-stats#:~:text=iMessage%20Monthly%20Active%20Users,-Want%20a%20link&text=iMessage%20has%20approximately%201%20billion%20monthly%20active%20users.,re%20sending%20messages%20or%20not.][1.3 billion]]  |
| WeChat            | [[https://www.statista.com/statistics/255778/number-of-active-wechat-messenger-accounts/][1.3 billion]]  |
| Facebook Messager | [[https://datareportal.com/essential-facebook-messenger-stats][1 billion]]    |
| Telegram          | [[https://www.businessofapps.com/data/telegram-statistics/][500 million]]  |
| Twitter           | [[https://www.businessofapps.com/data/twitter-statistics/][400 million]]  |
| Discord           | [[https://www.bankmycell.com/blog/number-of-discord-users/][196 million]]  |
| Mastodon          | [[https://mastodon.social/@mastodonusercount/110685193172985140][13 million]]   |

/Note that iMessage comes default installed for iPhone users./

* Mastodon is a Twitter replacement

People are looking for something different than Twitter because
Twitter sucks.  Mastodon was designed to be different from Twitter
because Twitter sucks.

Twitter sucks because of the way that works and Twitter sucks because
of the way that it's run.

It makes little sense to complain that something offering an
alternative way of something different is, in fact, an alternative way
of doing something different.

* Freedom to run your own instance is dismissive

{{< toot "mastodon.social" 109723298732303895 >}}

Telling someone that they have the freedom to go build their own
instance isn't (necessarily) telling someone to fuck off.  (Maybe in
that case it was, I don't know the details.)

There are [[https://writefreesoftware.org/learn][4 software freedoms]] that geeks talk about, the freedom to
*use*, *study*, *improve*, and *share* your software.

The point is: you could.  Start up a Nazi site, start up a community
around knitting.  You own it, with all of the maintenance costs that
are implied with ownership, and it seems like a pain in the ass
frankly to run these servers.

But it's up to you.  There are no gate keepers.

It will then be your problem, and people can complain that they don't
like your politics.

* Principles are ideological zealotry

#+begin_quote
I would like to see Mastodon thrive. But the platform’s ideological
zealotry is obviously holding it back and seemingly isn’t going to
change.

[[https://daringfireball.net/linked/2023/06/23/bloonface-twitter-migration][Daring Fireball: WHY HAS MASTODON ADOPTION STALLED?]]
#+end_quote

Holding it back from what, exactly?  Do we think that the reason you
start up a Mastodon instance is to become the next Twitter?

(And as an aside, I'm not sure what Daring Fireball re-titled the
original article from "Why did the #TwitterMigration fail?" to "Why
has Mastodon adoption stalled?" which I think undersells what a
lunatic Bloonface seems to be.)

Darius Kazemi has a document on why you should [[https://runyourown.social/][run your own social
network]], and in it he sets the goal of having a maximum of 50 users.

#+begin_quote
The main reason to run a small social network site is that you can
create an online environment tailored to the needs of your community
in a way that a big corporation like Facebook or Twitter never
could. Yes, you can always start a Facebook Group for your community
and moderate that how you like, but only within certain bounds set by
Facebook. If you (or your community) run the whole site, then you are
ultimately the boss of what goes on. It is harder work than letting
Facebook or Twitter or Slack or Basecamp or whoever else take care of
everything, but I believe it's worth it.
#+end_quote

What does thriving mean if your goal is to nurture your community?  

* Social media is social

#+begin_quote
On traditional “social media” platforms, in particular YouTube, the
interactions are often not especially social. The platforms facilitate
a kind of intellectual consumption more-so than conversation:
conversations flow in one direction, from creator to audience, where
the creator produces and the audience consumes. I think a better term
for these platforms is “[[https://en.wikipedia.org/wiki/Parasocial_interaction][parasocial media]]”: they are optimized for
creating parasocial relationships more-so than social relationships.

[[https://drewdevault.com/2023/06/30/Social-and-parasocial-media.html][Drew DeVault]]
#+end_quote

Probably the best way to see this fallacy in action is reading about
[[https://wedistribute.org/2023/06/brands-town-is-where-the-brands-are/][Brands Town]], a [[https://wiki.brands.town/wiki/Brands_Town][culture-jamming satire project]].

#+begin_quote
Brands Town is a satirical role-playing game where players make up fake
brands, develop their own lore, and role-play on the related Mastodon
instance. Because Mastodon is part of the fediverse, this weird little
game takes on dimensions of performance art, parody, and creative
design. It doesn't stay on one server!

[[https://wiki.brands.town/wiki/Brands_Town][Brands Town]]
#+end_quote

