#+title: everything is equally evolved
#+tags[]: language
#+date: 2023-08-05T21:05:55

In /astronomy,/ the term /evolution/ refers to the production of elements,
stars, galaxies, and the other configuration of inorganic matter.

In /biology/, /evolution/ refers to the adaptions of organisms to their
environment through natural selection.

In /humans/, or the /psychosocial domain/, /evolution/ refers to a type of
human growth and civilizational development.

Each of these domains -- /inorganic/, /organic/, /psychosocial/ -- operate
on different principals.  They are related, but each one has
trancended the one previous.  /Inorganic/ evolution produces living
species, giving rise to /life/; /organic/ evolution produces intentional
beings, giving rise to to /consciousness/.

The third type of evolutionary trancendance isn't here yet, or at
least isn't widely distributed.

But if we think about the world and all of the things in it, its not
right to say that some things are more evolved than others in the
sense of better better or having progressed more; everything is as
equally evolved as everything else since it's all been evolving
together.
