#+title: hallucinations are bullshit
#+date: 2023-07-05T07:03:43
#+draft: true

A better word for /hallucations/ is really /bullshit/, which differs from
a more straightforward /falsehood/ because the speaker is blithely
unconcerned about truth.

It's not so much that these AI tools are /grounded in reality/ or
/hallucating/, telling /the truth/ or /misinformation/, as much as they
sound authoritiave when they do it.

#+begin_quote
Frankfurt proceeds by exploring how bullshit and the related concept
of humbug are distinct from lying. He argues that bullshitters
misrepresent themselves to their audience not as liars do, that is, by
deliberately making false claims about what is true. In fact, bullshit
need not be untrue at all. Rather, bullshitters seek to convey a
certain impression of themselves without being concerned about whether
anything at all is true.
#+end_quote

--- [[https://philpapers.org/rec/FRAOB][On Bullshit by Harry G. Frankfurt]]

/Also [[https://www.amazon.com/Bullshit-Harry-G-Frankfurt-ebook/dp/B001EQ4OJW?ref_=ast_author_mpb][available as an expanded book]]/
