#+title: locations in the magicians
#+date: 2023-08-22T09:43:43

[[https://levgrossman.com/books/the-magicians-a-novel/][The Magicians]] is one of those series of books that I enjoy rereading.
Not really sure why, but one thing that's surpising to me is how many
of the real world places that seem to have inspired the book are in my
orbit.

In Brooklyn, there are a couple of scenes were they hang out in a dead
zone near the Gowanus canal.  I had a wild neighbor who used to own if
not that exact spot, then something exactly like it.

"Brakebills" exists somewhere upstate near West Point, and I've spend
many hours in Bear Mountain.

I've ended up in Arles a couple of times, and wandered through the
back country around Murs when the gang went to look for ol' timy
religions.

Flying into the British Virgin Islands there was a passport problem
with one of our group, and that outpost was definately reminicint of
the end of Fillory.

At the end of the last book, they get into a big fight in the woods of
western Connecticut, which is where I live now.  They take a train
from Amenia back to the city, and I just got tacos in Amenia at this
strange mexican grocery store that could very well have been a front
for something.  Tacos were great though.
