#+title: political implications
#+tags[]: language
#+date: 2023-10-01T07:16:25

The Washington Post asks [[https://www.washingtonpost.com/climate-environment/2023/09/30/end-fossil-fuels-biden/][What the world would look like without fossil
fuels]], which can be summed up as "out entire way of existence
depends on a huge amount of energy almost all of which we get from
oil".  The rough idea they are explaining is that if we just stop
building more wells and mines, things will gradually get more
expensive and it will take a huge amount of time and resources to
transition to other sources, but turning it off directly is
unrealistic.

Overall it tells a nice story, but what struck me was a paragraph at the end:

#+begin_quote
“The biggest worry I have is: ‘What are the implications of the clean
energy transition in some of the segments of the population that are
badly affected?’” Birol said. “In a not very well-planned transition,
there could be a bit of a backlash with political implications.”
#+end_quote

Basically, the transition will hurt a bunch of people, specifically
the ones that are already under a smack-down.  "Backlash with political
implications".

How about humanitarian implications?  How about inequality, or general
unfairness?  Is the real problem here that it's politically
inconvenient?

Calling it "political" is such a euphemism. 
