#+title: Should Robots Have Rites or Rights
#+date: 2023-07-11T14:51:21
#+tags[]: ai philosophy

#+begin_quote
Here’s some food for thought: “Granting rights is not the only way to
address the moral status of robots: Envisioning robots as rites
bearers—not rights bearers—could work better.” A new paper, “[[https://dl.acm.org/doi/10.1145/3571721?utm_source=www.turingpost.com&utm_medium=referral&utm_campaign=prompt-engineer-vs-ai-engineer-and-superhuman-human-fallacy][Should
Robots Have Rites or Rights]],” suggests that “the Confucian
alternative of assigning rites (or role obligations) is more
appropriate than giving robots rights. The concept of rights is often
adversarial and competitive, and the potential for conflict between
humans and robots is concerning.”

[[https://www.turingpost.com/p/fod10][Turing Post FOD #10: Prompt Engineer vs AI Engineer, and Superhuman Human Fallacy]]
#+end_quote

[[https://dl.acm.org/doi/pdf/10.1145/3571721][Full PDF of the paper]]

Excerpts:

#+begin_quote
In Confucianism, individuals are made distinctively human by their
ability to conceive of interests not purely in terms of personal
self-interest—but instead in terms that also include a relational and
communal self. Etymologically, the meaning of humanness ( , ren) is
“two people.” The Confucian’s recognition of the communal self
requires a distinctive perspective on rite or ritual. The Chinese term
li ( , rite or ritual) symbolizes arranging vessels in a religious
setting. But Confucian texts used li outside the scope of religious
tradition. Examples abound, including friendship, gift giving, or
forms of speech. The rites that concern Confucius are quotidian
practices. Here is a modern example: “I see you on the street; I
smile, walk toward you, put out my hand to shake yours. And
behold—without any command, stratagem, force, special tricks or tools,
without any effort on my part to make you do so, you spontaneously
turn toward me, return my smile; raise your hand toward mine. We shake
hands—not by my pulling your hand up and down or you pulling mine but
by spontaneous and perfect cooperative action. Normally we do not
notice the subtlety and amazing complexity of this coordination ritual
act.”
#+end_quote
