#+title: the standardization of commerce
#+date: 2023-07-16T19:54:59

Timezones were created because of the trains.  Before, everyplace has
its own definition of noon, which was when the sun was at the highest.
First proposed in 1883, it was eventually [[https://www.up.com/customers/track-record/tr031020-time-zones.htm#:~:text=On%20November%2018%2C%201883%2C%20the,are%20still%20in%20place%20today.][signed into US law in 1918]]
as [[https://en.wikipedia.org/wiki/Standard_Time_Act][the Standard Time Act]].

Where do languages come from?  [[https://en.wikipedia.org/wiki/A_language_is_a_dialect_with_an_army_and_navy][A language is a dialect with an army
and navy]].

Where do dialects come from?  I think from books, or more
to the point publishers, who are trying to reach an audience and
market.  The more they publish in a certain dialect, the more that
dialect is defined and reflected back to itself.

The fluidity is then circumscribed a fixed by the commerce; in the
first case transportation, and in the second place by book publishers
and consumers.  Without those forces, everything would be fluid and
local.

So Yiddish, the Hasidim not withstanding, has more of a chance of
surviving because [[https://www.europarl.europa.eu/thinktank/en/document/EPRS_BRI(2022)698881#:~:text=As%20the%20use%20of%20Yiddish,language%20is%20not%20yet%20sealed.][of all of its published literature]].
