#+title: things that are neat about the rivian
#+date: 2023-07-06T08:56:54

* powered frunk hood

a button in the front will open and close the hood.  (The tesla is
manual and you sort of need to shove it closed.)  I end up using this
all the time.

Also, you can fill it with ice and it has a drain, so you can use it
as a cooler.  I haven't tried that yet.

* hotspot and cell service

The Rivian consistently has service when my phone doesn't.  Connecting
the phone to the car's built in hotspot means that I can even sort of
stream music or podcasts from the phone up here in the woods.

Sort of.

* fast voice command

We play a game in the car where the kids get to choose a song based on
the order that they buckle up.  So there's a lot of "play the worlds
smallest violin" or "play start a riot".  Using the button on the
steering wheel, the voice command on the rivian is significantly
faster than on the Tesla.

* the front glows when you charge

{{< toot "floss.social" 110667245486018156 >}}

* there's a flashlight in the door

Which uses the same battery cell as the car.  There's also a speaker
you can remove from the car and use I guess during your picnic party.
