#+title: Feed reading in emacs
#+subtitle: Using elfeed-org
#+tags[]: howto, emacs
#+date: 2020-06-17
#+draft: true

Lets use elfeed-org to keep track of our feeds, and then we'll use
elfeed to actually read them.  Lets go!

* Installation

=M-x package-install RET elfeed-org= and =M-x package-install RET
elfeed-goodies=

Stick this in your =.emacs= file:

#+begin_src emacs-lisp
(require 'elfeed-org)
(elfeed-org)

;;(require 'elfeed-goodies)
;;(elfeed-goodies/setup)

(global-set-key (kbd "C-x w") 'elfeed)

#+end_src

#+RESULTS:
: elfeed
* Adding browsing with =eww=

Pressing =b= will normally bring up a webbrowser to view the page, but I
often find it nicer to stay within emacs.  So we'll add a quick
function that will let us open the entry's link in =eww= and bind it to
=B= in the correct mode-map.

#+begin_src emacs-lisp
(defun elfeed-eww-browse ()
  "Wrapper to open eww and mark elfeed as read"
  (interactive)
  (let ((link (elfeed-entry-link elfeed-show-entry)))
    (when link
      (eww-browse-url link))))

(define-key elfeed-show-mode-map (kbd "B") 'elfeed-eww-browse)
#+end_src
* Setting up [[https://github.com/remyhonig/elfeed-org][elfeed-org]]

By default =elfeed-org= stores its configuration in =.emacs.d/elfeed.org=.
We can edit this by hand, or start with importing an =OMPL= file from
whatever you were using previously.

Run =M-x elfeed-org-import-opml=.  My ile is 374 lines long, many of
which dont seem to exist anymore!  Its interesting to go look at
these, and to see which ones are still around.  Some haven't been
updated in years. Maybe that's not the most effective way to do
things.

* Retagging

=M-x elfeed-apply-autotags-now= will let apply autotags for feeds if you
are editing your master list.

* References
1. https://nullprogram.com/blog/2013/09/04/
2. http://pragmaticemacs.com/emacs/read-your-rss-feeds-in-emacs-with-elfeed/
3. https://github.com/remyhonig/elfeed-org
4. https://noonker.github.io/posts/2020-04-22-elfeed/
5. http://pragmaticemacs.com/emacs/to-eww-or-not-to-eww/
