#+title: Beginning Emacs for JavaScript Development
#+subtitle: Rediscovering emacs
#+tags[]: emacs, javascript, floss
#+date: 2019-07-16
#+draft: true

I've dipped back into the world of Free Software, a place that I used to know very well and it's now even better than I remember it.  I love the package manager!  I've started using emacs again -- a lot of the muscle memory is still there.  Lets look at how to setup emacs to do JavaScript development.

First install emacs.  You need emacs > 25 to use magit, so its probable that you'll need to upgrade the emacs in your system.  If you are using linux I'll let you sort that out directly, but below are the instructions for OSX.

* Using homebrew to install emacs on OSX

#+BEGIN_SRC bash
brew cask install emacs
#+END_SRC


If you are on OSX you'll also need to install some certs, and defined in [[https://blog.vifortech.com/posts/emacs-tls-fix/][this wonderful walkthrough.]]  Simply:

#+BEGIN_SRC bash
brew install libressl
#+END_SRC

And then in =.emacs= add

#+BEGIN_SRC elisp
(require 'gnutls)
(add-to-list 'gnutls-trustfiles "/usr/local/etc/openssl/cert.pem")
#+END_SRC


* Changing the capslock key to control

Go into =System Preferences...= -> =Keyboard= and select =Modifier Keys=.  Switch caps lock key to be control.  Totally worth it, but you still need to do a META dance with the options key, instead of the more obvious command key.

* Emacs super basics

Emacs is something much more than an editor.  It's an environment within which you can interact with your computer that could replace many of the tools that you use now.  I normally use Terminal for example to interact with things and open up other programs to do specific tasks.  Emacs could replace terminal, as well as all of the programs that are used to get into the nitty gritty of making computers do what you want.  I recommend the [[https://www.masteringemacs.org/][Mastering Emacs]] book as a great way to get started in your emacs journey.

** Aborting and quitting
- =ESC ESC ESC= will get you out of most messes
- =C-g C-g C-g= will also get you out
- =C-x C-x= will exit emacs
- =C-x C-z= will minimize emacs

** Files
- =C-x C-f= open a file
- =C-x C-s= save a file

** Moving around

- =Control= is by character, =Meta= is by word.
- /Modifier/-=f= moves the cursor forward, /Modified/-=b= moves the cursor back.
- /Modifier/-=d= deletes
- =C-A= is the beginning of the line, =M-A= is the beginning of the paragraph.
- =C-E= is the end of the line, =M-E= is the end of the sentence.
- =M-<= is the begining of the documement, =M->= is the end.
- =C-s= starts interactive search within the document

** Windows
- =C-x-1= makes the current window full screen
- =C-x-2= split horizontally
- =C-x-3= split vertically
- =C-x-o= switch focus


* Adding a new package registry

=M-x customize= and search for =package-archives=.  Insert a new one and add =https://stable.melpa.org/packages/=.  You can paste into emacs using =C-y=

Then =Apply and Save=

Refresh the package list using =M-x refresh-package-contents=

* Install rjsx-mode and xref-js2

I mainly do react development on the front end, and the =rjsx-mode= depends on the =js2-mode= which is pretty great.  We'll install this and =xref-js2= to help navigate through files better.

=M-x package-install= then =rjsx-mode=

=M-x package-install= then =xref-js2=

And add to your =~/.emacs=

#+BEGIN_SRC elisp
(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))
#+END_SRC

You can use the mouse to select -- or =C-space= to select the start of the region and move the pointer around. Once you have the region selected do =M-x eval-buffer= to load the config in place.

* Install =magit=

=M-x package-install RET magit=.

Inside of =.emacs= add:

#+BEGIN_SRC elisp
(global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

Magit is amazingly powerful, and I'm still trying to learn it.



* References

1. https://www.masteringemacs.org/
2. https://blog.vifortech.com/posts/emacs-tls-fix/
3. https://gist.github.com/CodyReichert/9dbc8bd2a104780b64891d8736682cea
3. https://emacs.cafe/emacs/javascript/setup/2017/04/23/emacs-setup-javascript.html
4. https://github.com/felipeochoa/rjsx-mode
