models:
  gemma4:
    cmd: llama-server --port ${PORT} -hf unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_M --ctx-size 0
    ttl: 120
    aliases:
      - gemma-4-26b

  gemma4-31b:
    cmd: llama-server --port ${PORT} -hf unsloth/gemma-4-31B-it-GGUF:Q4_K_M --ctx-size 0
    ttl: 120
    aliases:
      - gemma-4-31b

  gemma4-e2b:
    cmd: llama-server --port ${PORT} -hf unsloth/gemma-4-E2B-it-GGUF:Q4_K_M --ctx-size 0
    ttl: 120

  nemotron:
    cmd: llama-server --port ${PORT} -hf unsloth/Nemotron-3-Nano-30B-A3B-GGUF:Q4_K_M --ctx-size 0
    ttl: 120
    aliases:
      - nemotron-3-nano

  nemotron-4b:
    cmd: llama-server --port ${PORT} -hf unsloth/NVIDIA-Nemotron-3-Nano-4B-GGUF:Q8_0 --ctx-size 0
    ttl: 120

  qwen3:
    cmd: llama-server --port ${PORT} -hf unsloth/Qwen3-30B-A3B-GGUF:Q4_K_M --ctx-size 0
    ttl: 120
    aliases:
      - qwen3-30b

  qwen3-32b:
    cmd: llama-server --port ${PORT} -hf unsloth/Qwen3-32B-GGUF:Q4_K_M --ctx-size 0
    ttl: 120

  qwen3-coder:
    cmd: llama-server --port ${PORT} -hf unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q4_K_M --ctx-size 0
    ttl: 120
    aliases:
      - qwen-coder
