version: '3.7'
services:
  whoami:
    image: containous/whoami
    networks:
      - caddy
    labels:
      caddy: apple.willschenk.com
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
