FROM python:3.8-slim

# Install git and required packages
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Clone waybackpack repository
RUN git clone https://github.com/jsvine/waybackpack.git /waybackpack

# Install waybackpack
WORKDIR /waybackpack
RUN python setup.py install

# Set working directory
WORKDIR /websites

# Set entrypoint
ENTRYPOINT ["waybackpack"]
