#!/bin/bash

if [ -z "$2" ]
then
    echo "Usage: $0 <url> <timestamp>"
    echo "eg: $0 http://sublimeguile.com 20040803021022"
    exit 1
fi


# Run the downloader
docker run --rm -it \
       -v $PWD/websites:/websites \
       -v $PWD/text:/text \
       rubydownloader -t $2 --concurrency 20 -d /websites/$2  $1

#!/bin/bash

if [ -z "$2" ]
then
    echo "Usage: $0 <url> <timestamp>"
    echo "eg: $0 http://sublimeguile.com 20040803021022"
    exit 1
fi


# Run the downloader
docker run --rm -it \
       -v $PWD/websites:/websites \
       -v $PWD/text:/text \
       rubydownloader -t $2 --concurrency 20 -d /websites/$2  $1
